version: '3.8'

services:
  backend:
    build: ./backend-Django
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SECRET_KEY=yXSycDk8NKpZ4uv214jGORbqsap7BnAUi5BTzpNRDzjbbF6kiU_qc5oqjvqJ8yu1-54
      - DEBUG=False
      - ALLOWED_HOSTS=yourdomain.com
      - CONTACT_FORM_RECIPIENT=kouamejeantrinite@gmail.com
    volumes:
      - ./backend-Django/media:/app/media
    restart: unless-stopped

  frontend:
    build: ./portfolio-angular-Kouame-jean-Raphael-Trinite
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  media:
